### ISSUE TITLE
Patch #337 needed anymore?

### ISSUE THREAD

**Issue by ahmdt** [fzyzcjy/flutter_convenient_test#364] opened 2024-01-26 09:39 UTC
Hi, is this message needed or can we create an workaround for newer flutter versions?

`binding.runningAsyncTasks` does not exist. Follow #337 to patch the code to get it.

**Comment by fzyzcjy** [comment] 2024-01-26 10:00
Hi, IIRC it is still needed, because Flutter did not merge the proposal (see https://github.com/flutter/flutter/issues/126545). However, feel free to PR to workaround it!

**Comment by ahmdt** [comment] 2024-01-26 13:21
Seems not to be continued on flutter side. What may be a good workaround approach?

**Comment by fzyzcjy** [comment] 2024-01-26 13:38
On one hand, you can workaround by manually patching as is suggested in #337. On the other hand, https://github.com/flutter/flutter/issues/126545 has some suggestions (e.g. subclass TestWidgetsFlutterBinding).

**Comment by Tomburgs** [comment] 2024-02-23 10:42
How _do_ you patch it, @fzyzcjy? 

I've tried creating a duplicate of flutter_test to include this patch and then referenced it in pubspec with the `path: ./patched_flutter_test` argument, but that causes issues as many other dependencies, including flutter_convenient_test depend on the sdk version.

I'm also curious how difficult would it be to implement a fix in this project so that we don't have to go patching other libraries?

**Comment by fzyzcjy** [comment] 2024-02-23 11:55
I personally just modify the flutter framework code itself. (I use git patch apply and a small script, but any method works).

> I'm also curious how difficult would it be to implement a fix in this project so that we don't have to go patching other libraries?

IIRC I examined it a little bit a long time ago and found some things may not work well, but to be honest I forgot what I tried (it may work indeed and just because I was too tired at that time). I will try to find some time to have a look at it later.

**Comment by lunakoan** [comment] 2024-04-21 01:10
Modifying the flutter code directly is a bit daunting 😬  Is there any way to make use of this library more seamless, such as a small bash script to modify the binding before/after each run or having a custom binding as suggested [here](https://github.com/flutter/flutter/issues/126545#issuecomment-1551960447)? I am happy to help with this, just not sure where to start..

**Comment by fzyzcjy** [comment] 2024-04-21 01:30
I guess the first approach is possible (just some git-apply-patch things), and the second may also work. To get started on the first approach, maybe firstly play with git patch commands by hand and then create a script; for the second one, maybe firstly have a high-level overview of flutter testing bindings logic.

**Closed** 2024-06-29 05:21 UTC
Labels: wontfix
